config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
  	resources :comments
  end
  root "posts#index"
  get '/about', to: 'pages#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :name, presence: true, length: { minimum: 5}
  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: { minimum: 5}
	validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(comment_params)
		redirect_to post_path @post
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path @post

	end
	
	private
	def comment_params
		params.require(:comment).permit(:name, :body)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	before_action :get_post, except: [:index, :create, :new ]

	def index
		@posts = Post.all.order('created_at DESC')
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			redirect_to posts_path
		else
			render 'new'
		end
	end

	def show
	end

	def update
		if @post.update_attributes(post_params)
			redirect_to post_path @post
		else
			render 'edit'
		end
	end

	def destroy
		if @post.destroy
			redirect_to root_path
		#else
			#render 'edit'
		end		
	end

	private

	def post_params
		params.require(:post).permit(:title, :body)
	end

	def get_post
		@post = Post.find(params[:id])
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %> </strong></p>	
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_title"> <%= time_ago_in_words(comment.created_at) %> ago </p>

	</div>
	<% if user_signed_in? %>
		<p> <%= link_to 'Delete', [comment.post, comment], method: :delete, class: "button", data: { confirm: "Are you sure?" } %> </p>
	<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for ([@post, @post.comments.build]) do |f| %>
	<p> 
		<%= f.label :name %> <br />
		<%= f.text_field :name %> 
	</p>
	<p>
		<%= f.label :content %> <br />
		<%= f.text_area :body %> 
	</p>
	<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tumblrr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Raleway:400,700' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico.png' %>
  </head>

  <body>
  	<div id="sidebar">
      <ul>
        <li class="category"> <%= link_to "Tumblr", root_path %> </li>
        <li> <%= link_to "Posts", root_path %></li>
        <li> <%= link_to "About", about_path %></li>
      </ul>
      <% if !user_signed_in? %>
        <p class="sign_in"> <%= link_to "User login", new_user_session_path %> </p>
      <% end %>
    </div>

    <div id="main_content">
      <div id="header">
        <% if current_page?(root_path) %>
           <p> Post feed </p>
        <% elsif current_page?(about_path) %>
            <p> My Site </p>
        <% else %>
            <%= link_to "Back to post feed", root_path %>
        <% end %>
        
        <% if user_signed_in? %>  
          <div style="float: right"> 
            <!-- <button class="button"> -->
             <%= link_to "Make Post", new_post_path, class: "button" %> 
           <!-- </button> -->
            <%= link_to "logout", destroy_user_session_path, method: :delete, class: "button" %>
          </div>
        <% end %>    
        <% flash.each do |key,msg| %>
          <%= content_tag(:div, msg, class: "alert") %>
        <% end %>
    
      </div>
  		<%= yield %>
  	</div> -->
    
  </body>
</html>

app/views/pages/about.html.erb
<div id="page_wraper">
	<div id="profile_image">
		<%= image_tag "profile_avatar.jpeg" %>
	</div>

	<div style="padding-left: 35px;">
		<h1> Its Mr Cipher </h1>
		<p>
			ose Uribe and his girlfriend Zulma Rodriguez back in Colima, Mexico, a region of around 650,000 on the Pacific coast. They worked over an entire summer from Uribe’s childhood bedroom, building the original algorithm that matched drivers and riders. After Uber was formed in San Francisco in 2010, the company’s early engineers were mystified as to why much of the original code was in Spanish. The story is not all that unusual in Silicon Valley, where technology firms 
		</p>
	</div>
</div>

app/views/posts/_form.html.erb
<%= form_for :post, url: posts_path do |f| %>
	<p> 
		<%= f.label :title %> <br />
		<%= f.text_field :title %> 
	</p>
	<p>
		<%= f.label :content %> <br />
		<%= f.text_area :body %> 
	</p>
	<%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<div class="page-wraper">
	<h2> Editing the post </h2>
	<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
		<div class="post_wrapper">
			<h2 class="title"><%= link_to post.title, post %> </h2>
		</h1>

		<p class="body">
			<%= truncate( post.body, length: 100 ) %>
		</p>

		<p class="date">
			Submitted <%= time_ago_in_words(post.created_at) %> ago
		</p>
	</div>
	
<% end %>

app/views/posts/new.html.erb
<div id="page_wraper">
	<h1> Creating a new post </h1>
	<%= render 'form' %>
</div>                                                                                                                                                                                         

app/views/posts/show.html.erb
<div id="post_content">
	<h1 class="title">
		<%= @post.title %>
	</h1>

	<p class="date">
		Submitted <%= time_ago_in_words(@post.created_at) %> ago
		<% if user_signed_in? %>
			<%= link_to "Edit", edit_post_path(@post) %> |
			<%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure ?"}  %>
		<% end %>
	</p>

	<p class="body">
		<%= @post.body %>
	</p>

	<div class="comments">
		<h2> <%= @post.comments.count %> Comments</h2>
			<%= render @post.comments %>
		<% if user_signed_in? %>	
			<h3> Join discussion </h3>
			<%= render 'comments/form' %>
		<% end %>
	</div>
</div>